id: I790E2927
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T12:10:33+00:00'
last_modified: '2022-06-07T10:27:25.871992+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14473
  title: འཇམ་དཔལ་གཤིན་རྗེའི་གཤེད་ཁྲོ་ཆུ་དུག་སྡོང་ནག་པོའི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C0DC:
      image_group_id: I1KG14477
      title: Volume 1 of 'jam dpal gshin rje'i gshed khro chu dug sdong nag po'i chos
        skor/
      total_pages: 568
      order: 1
      base_file: C0DC.txt
    B5FA:
      image_group_id: I1KG14478
      title: Volume 2 of 'jam dpal gshin rje'i gshed khro chu dug sdong nag po'i chos
        skor/
      total_pages: 562
      order: 2
      base_file: B5FA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
